print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
altura: float = float(input("Qual a sua altura?"))
print(f"A sua altura é {altura}")
peso: float = float(input("Qual o seu peso?"))
print(f"O seu peso é {peso}")
