print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade: int = int(input("Qual é a sua idade? "))
print(f"Tu tens {idade} anos...")
altura: float = float(input("Qual a sua altura?"))
print(f"A sua altura é {altura}")
peso: float = float(input("Qual o seu peso?"))
print(f"O seu peso é {peso}")
print(f"O seu IMC é: {peso/(altura**2)}")
cidade: str = str(input("Onde você nasceu?"))
dia_de_nascimento: int = int(input("Que dia do mês você nasceu?"))
mês_de_nascimento_de_nascimento: str = str(input("Que mês você nasceu?"))
ano_de_nascimento_de_nascimento: int = int(input("Que ano você nasceu?"))